/** Application constants. */

import type { TreeSpecies } from '../types/tree'

export const TREE_SPECIES: TreeSpecies[] = [
  { id: 'tree1',  name: '花楸',   description: '白花似雪，点缀春枝', color: '#6B8E23', variantCount: 1 },
  { id: 'tree2',  name: '黑松',   description: '苍劲挺拔，傲立风霜', color: '#1B5E20', variantCount: 1 },
  { id: 'tree3',  name: '白樱',   description: '素雅洁白，清丽脱俗', color: '#F5F5F5', variantCount: 1 },
  { id: 'tree4',  name: '染井吉野', description: '满树粉霞，如梦似幻', color: '#FFB7C5', variantCount: 1 },
  { id: 'tree5',  name: '垂柳',   description: '万条垂下，轻柔似水', color: '#5DAE5F', variantCount: 1 },
  { id: 'tree6',  name: '海棠',   description: '红果累累，秋意盎然', color: '#C0392B', variantCount: 1 },
  { id: 'tree7',  name: '金桂',   description: '金秋飘香，满树金黄', color: '#D4A017', variantCount: 1 },
  { id: 'tree8',  name: '青冈栎', description: '四季常青，坚韧不拔', color: '#2E7D32', variantCount: 1 },
  { id: 'tree9',  name: '银杏',   description: '扇叶金黄，秋之使者', color: '#F9A825', variantCount: 1 },
  { id: 'tree10', name: '红枫',   description: '霜叶如火，灿若云霞', color: '#D84315', variantCount: 1 },
  { id: 'tree11', name: '五彩枫', description: '层林尽染，色彩斑斓', color: '#E65100', variantCount: 1 },
  { id: 'tree12', name: '晚枫',   description: '深秋残叶，别有韵味', color: '#BF360C', variantCount: 1 },
  { id: 'tree13', name: '雪松',   description: '塔形挺秀，四季翠绿', color: '#1B5E20', variantCount: 1 },
  { id: 'tree14', name: '白桦',   description: '树皮如雪，亭亭玉立', color: '#D7CCC8', variantCount: 1 },
  { id: 'tree15', name: '雾凇松', description: '银装素裹，冰雪奇观', color: '#B3E5FC', variantCount: 1 },
  { id: 'tree16', name: '冬松',   description: '雪压青松，松更挺拔', color: '#81D4FA', variantCount: 1 },
  { id: 'tree17', name: '冬桦',   description: '寒林独立，静待春归', color: '#ECEFF1', variantCount: 1 },
  { id: 'tree18', name: '枯柳',   description: '虬枝盘曲，沧桑之美', color: '#795548', variantCount: 1 },
  { id: 'tree19', name: '晚樱',   description: '花叶同期，粉绿相映', color: '#F48FB1', variantCount: 1 },
  { id: 'tree20', name: '金枫',   description: '满树金辉，秋之礼赞', color: '#FF8F00', variantCount: 1 },
  { id: 'tree21', name: '榉树',   description: '冠幅圆润，生机盎然', color: '#43A047', variantCount: 1 },
  { id: 'tree22', name: '紫叶李', description: '紫叶红妆，别样风姿', color: '#9B3A6A', variantCount: 1 },
  { id: 'tree23', name: '水柳',   description: '临水而生，绿荫如盖', color: '#66BB6A', variantCount: 1 },
  { id: 'tree24', name: '冷杉',   description: '高寒之友，傲雪凌霜', color: '#2E7D32', variantCount: 1 },
  { id: 'tree25', name: '白桦春', description: '新叶初绽，春意盎然', color: '#A5D6A7', variantCount: 1 },
  { id: 'tree26', name: '梧桐',   description: '梧桐叶落，知秋一叶', color: '#388E3C', variantCount: 1 },
  { id: 'tree27', name: '白桦秋', description: '金叶白干，秋色醉人', color: '#FFB300', variantCount: 1 },
  { id: 'tree28', name: '白桦暮', description: '夕照金辉，静美如画', color: '#FFC107', variantCount: 1 },
  { id: 'tree29', name: '蜜蜡枫', description: '琥珀流光，秋韵悠长', color: '#FF8F00', variantCount: 1 },
  { id: 'tree30', name: '苹果树', description: '硕果累累，丰收喜悦', color: '#D4524B', variantCount: 1 },
  { id: 'tree31', name: '古枫',   description: '老干虬枝，岁月沧桑', color: '#E65100', variantCount: 1 },
  { id: 'tree32', name: '山楂',   description: '红果满枝，酸甜可口', color: '#C62828', variantCount: 1 },
  { id: 'tree33', name: '雾凇桦', description: '玉树琼枝，冬日仙境', color: '#E1F5FE', variantCount: 1 },
  { id: 'tree34', name: '海棠果', description: '小果红艳，缀满枝头', color: '#EF5350', variantCount: 1 },
  { id: 'tree35', name: '香樟',   description: '四季常绿，清香宜人', color: '#558B2F', variantCount: 1 },
  { id: 'tree36', name: '朴树',   description: '树形优美，遮荫避日', color: '#4CAF50', variantCount: 1 },
  { id: 'tree37', name: '梨树',   description: '春华秋实，金果飘香', color: '#C0CA33', variantCount: 1 },
]

export const GROWTH_LABELS = ['种子', '萌芽', '树苗', '大树'] as const
